/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.wenxin.natureplus;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.biome.Biome;
import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class NatureplusModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public NatureplusModElements() {
		sounds.put(new ResourceLocation("natureplus", "kernel_pult"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "kernel_pult")));
		sounds.put(new ResourceLocation("natureplus", "cactus_shoot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "cactus_shoot")));
		sounds.put(new ResourceLocation("natureplus", "splat"), new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "splat")));
		sounds.put(new ResourceLocation("natureplus", "peashooter_shoot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "peashooter_shoot")));
		sounds.put(new ResourceLocation("natureplus", "planting"), new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "planting")));
		sounds.put(new ResourceLocation("natureplus", "planting_water"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "planting_water")));
		sounds.put(new ResourceLocation("natureplus", "shovel"), new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "shovel")));
		sounds.put(new ResourceLocation("natureplus", "snow_pea_shoot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "snow_pea_shoot")));
		sounds.put(new ResourceLocation("natureplus", "balloon_inflate"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "balloon_inflate")));
		sounds.put(new ResourceLocation("natureplus", "balloon_pop"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "balloon_pop")));
		sounds.put(new ResourceLocation("natureplus", "balloon_rub"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "balloon_rub")));
		sounds.put(new ResourceLocation("natureplus", "bug_squish"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "bug_squish")));
		sounds.put(new ResourceLocation("natureplus", "butterfly_flying"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "butterfly_flying")));
		sounds.put(new ResourceLocation("natureplus", "duck_ambient"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "duck_ambient")));
		sounds.put(new ResourceLocation("natureplus", "squitch"), new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "squitch")));
		sounds.put(new ResourceLocation("natureplus", "swoosh"), new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "swoosh")));
		sounds.put(new ResourceLocation("natureplus", "vase_breaking"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "vase_breaking")));
		sounds.put(new ResourceLocation("natureplus", "zombie_gulp"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "zombie_gulp")));
		sounds.put(new ResourceLocation("natureplus", "cactus_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "cactus_death")));
		sounds.put(new ResourceLocation("natureplus", "cactus_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "cactus_hurt")));
		sounds.put(new ResourceLocation("natureplus", "duck_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "duck_death")));
		sounds.put(new ResourceLocation("natureplus", "duck_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "duck_hurt")));
		sounds.put(new ResourceLocation("natureplus", "sunflower_collect"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "sunflower_collect")));
		sounds.put(new ResourceLocation("natureplus", "throw"), new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "throw")));
		sounds.put(new ResourceLocation("natureplus", "zombie_bite"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "zombie_bite")));
		sounds.put(new ResourceLocation("natureplus", "spike_hit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("natureplus", "spike_hit")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("natureplus").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == NatureplusModElements.ModElement.class)
						elements.add((NatureplusModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(NatureplusModElements.ModElement::initElements);
		MinecraftForge.EVENT_BUS.register(new NatureplusModVariables(this));
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}
	private int messageID = 0;
	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		NatureplusMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final NatureplusModElements elements;
		protected final int sortid;
		public ModElement(NatureplusModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
