modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="natureplus"
version="1.0"
displayName="Nature +"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="WenXin2"
description='''
This mod adds blocks & items related to nature.
'''

[[dependencies.natureplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




