
// Date: 5/30/2018 11:56:28 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX








public static class ModelKoalaBear extends ModelBase
{
//fields
ModelRenderer head;
ModelRenderer body;
ModelRenderer leg1;
ModelRenderer leg2;
ModelRenderer leg3;
ModelRenderer leg4;
ModelRenderer nose;
ModelRenderer ear1;
ModelRenderer ear2;
ModelRenderer tail;

public ModelKoalaBear()
{
textureWidth = 64;
textureHeight = 32;

head = new ModelRenderer(this, 0, 0);
head.addBox(-4F, -4F, -8.5F, 6, 6, 6);
head.setRotationPoint(1F, 15F, -2.733333F);
head.setTextureSize(64, 32);
head.mirror = true;
setRotation(head, 0F, 0F, 0F);
body = new ModelRenderer(this, 28, 8);
body.addBox(-5F, -10F, -7F, 8, 14, 6);
body.setRotationPoint(1F, 12F, 3F);
body.setTextureSize(64, 32);
body.mirror = true;
setRotation(body, 1.570796F, 0F, 0F);
leg1 = new ModelRenderer(this, 0, 16);
leg1.addBox(-2F, 0F, -2F, 3, 5, 3);
leg1.setRotationPoint(-2F, 19F, 6F);
leg1.setTextureSize(64, 32);
leg1.mirror = true;
setRotation(leg1, 0F, 0F, 0F);
leg2 = new ModelRenderer(this, 0, 16);
leg2.addBox(-2F, 0F, -2F, 3, 5, 3);
leg2.setRotationPoint(3F, 19F, 6F);
leg2.setTextureSize(64, 32);
leg2.mirror = true;
setRotation(leg2, 0F, 0F, 0F);
leg3 = new ModelRenderer(this, 0, 16);
leg3.addBox(-2F, 18F, -2F, 3, 5, 3);
leg3.setRotationPoint(-2F, 1F, -5F);
leg3.setTextureSize(64, 32);
leg3.mirror = true;
setRotation(leg3, 0F, 0F, 0F);
leg4 = new ModelRenderer(this, 0, 16);
leg4.addBox(-2F, 0F, -2F, 3, 5, 3);
leg4.setRotationPoint(3F, 19F, -5F);
leg4.setTextureSize(64, 32);
leg4.mirror = true;
setRotation(leg4, 0F, 0F, 0F);
nose = new ModelRenderer(this, 15, 16);
nose.addBox(0F, 0F, 0F, 2, 2, 1);
nose.setRotationPoint(-1F, 14F, -11.5F);
nose.setTextureSize(64, 32);
nose.mirror = true;
setRotation(nose, 0F, 0F, 0F);
ear1 = new ModelRenderer(this, 28, 0);
ear1.addBox(0F, 0F, 0F, 3, 3, 1);
ear1.setRotationPoint(1F, 10F, -10.5F);
ear1.setTextureSize(64, 32);
ear1.mirror = true;
setRotation(ear1, 0F, 0F, 0F);
ear2 = new ModelRenderer(this, 39, 0);
ear2.addBox(0F, 0F, 0F, 3, 3, 1);
ear2.setRotationPoint(-4F, 10F, -10.5F);
ear2.setTextureSize(64, 32);
ear2.mirror = true;
setRotation(ear2, 0F, 0F, 0F);
tail = new ModelRenderer(this, 15, 21);
tail.addBox(0F, 0F, 6.5F, 2, 2, 1);
tail.setRotationPoint(-1F, 15F, 0F);
tail.setTextureSize(64, 32);
tail.mirror = true;
setRotation(tail, 0F, 0F, 0F);
}

public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
{
super.render(entity, f, f1, f2, f3, f4, f5);
setRotationAngles(f, f1, f2, f3, f4, f5, entity);

head.render(f5);
body.render(f5);
leg1.render(f5);
leg2.render(f5);
leg3.render(f5);
leg4.render(f5);
nose.render(f5);
ear1.render(f5);
ear2.render(f5);
tail.render(f5);
}

private void setRotation(ModelRenderer model, float x, float y, float z)
{
model.rotateAngleX = x;
model.rotateAngleY = y;
model.rotateAngleZ = z;
}

public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)

{
super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
this.head.rotateAngleY = f3 / (180F / (float)Math.PI);
this.head.rotateAngleX = f4 / (180F / (float)Math.PI);
this.leg2.rotateAngleX = MathHelper.cos(f * 1.0F) * -1.0F * f1;
this.leg1.rotateAngleX = MathHelper.cos(f * 1.0F) * 1.0F * f1;

}

}